# Generated by Django 5.1.4 on 2025-01-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0002_remove_lesson_is_complete_remove_lesson_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
            ],
        ),
    ]
