# Generated by Django 5.1.4 on 2025-01-10 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0004_image_resource_sound_video_comment_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
