# Generated by Django 5.1.4 on 2025-01-11 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0006_reply_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
